import { Box, Button, Flex, FormControl, FormLabel, Heading, Input, Text, Textarea } from '@chakra-ui/react'
import Head from 'next/head'
import {  FunctionComponent } from 'react';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup'

// criando com Lib react-hook-form

interface IUserFormData{
  firstName: string,
  lastName: string,
  email:string,
  address: string,
  phone: string,
  description: string,
  handleSubmit: () => void,
  onSubmit: () => void,
}

const schema = yup.object({
  firstName: yup.string().required(),
  lastName: yup.string().required(),
  email: yup.string().required(),
  address: yup.string().required(),
  phone: yup.string().required(),
  description: yup.string().required(),
})

const  Cadastro: FunctionComponent = () => {

  const {
    register, 
    handleSubmit, 
    formState: { errors }} = useForm<IUserFormData>({
    resolver: yupResolver(schema)
  });

  function onSubmit(data: IUserFormData){
      console.log(data)
  }

 
  return (
    <>
      <Head>
        <title>Form com NextJS e Chakra UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Flex
          minHeight='100vh'
          width='full'
          align='center'
          justifyContent='center'
          backgroundColor='gray.900'
        >
          <Box px={12} py={12} width='full' maxWidth='450px' textAlign='center'
            boxShadow='lg' borderRadius='6px' background='gray.700'>
            <Heading>
              <Text color='gray.200' fontSize='2xl'>
                Formulário de Registro
              </Text>
            </Heading>
            <Box>
              <form action="" autoComplete='off' onSubmit={handleSubmit(onSubmit)}>
                <Flex justify='space-between'>
                <FormControl  marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >First Name</FormLabel>
                  <Input 
                  type='text' 
                  border='none' 
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='first Name'
                  {...register('firstName')}
                  />
                  <p style={{color:'red'}}>{errors.firstName?.message}</p>
                </FormControl>
                <FormControl   marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >Last Name</FormLabel>
                  <Input 
                  type='text'
                  border='none' 
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Last Name'
                  {...register('lastName')}
               />
                  <p style={{color:'red'}}>{errors.lastName?.message}</p>
                </FormControl>
                </Flex>
                <FormControl   marginTop='15px' >
                  <FormLabel color='gray.200' > Your e-mail</FormLabel>
                  <Input 
                  type='text' 
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Your E-mail'
                  {...register('email')}
                 />
                  <p style={{color:'red'}}>{errors.email?.message}</p>
                </FormControl>
                <Flex justify='space-between' >
                <FormControl   marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >Your address</FormLabel>
                  <Input 
                  type='text' 
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Your Address'
                  {...register('address')}
                />
                  <p style={{color:'red'}}>{errors.address?.message}</p>
                </FormControl>
                <FormControl   marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >Your phone</FormLabel>
                  <Input 
                  type='number'
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Your Phone'
                  {...register('phone')}
             />
                  <p style={{color:'red'}}>{errors.phone?.message}</p>
                </FormControl>
                </Flex>
                <FormControl   marginTop='15px'>
                  <FormLabel color='gray.200' >Your descript message</FormLabel>
                  <Textarea 
                    outline='none'   
                    bgColor='gray.900' 
                    focusBorderColor='gray.600' 
                    color='gray.200' 
                    placeholder='Your descript message'
                    resize='none'
                    {...register('description')}
                    />
                    <p style={{color:'red'}}>{errors.description?.message}</p>
                </FormControl>
        
                <Button
                  type='submit'
                  width='full'
                  bgColor='green.400'
                  mt={4}
                  color='gray.200'
                  _hover={{color: 'black'}}
                >Cadastro</Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  )
}

export default Cadastro;
