import { Box, Button, Flex, FormControl, FormLabel, Heading, Input, Text, Textarea } from '@chakra-ui/react'
import Head from 'next/head'
import { FormEvent, FunctionComponent, useState } from 'react';

// criando sem Lib
interface IHomeProps{
  fistName: string,
  lastName: string,
  email: string,
  address: string,
  phone: string,
  description: string,
}

const  Home: FunctionComponent<IHomeProps> = () => {
  const [fistName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');  
  const [address, setAddress] = useState('');
  const [phone, setPhone] = useState('');
  const [description, setDescription] = useState('');  

  const handlerSubmit = (e: FormEvent) => {
    e.preventDefault();

    const data = { 
      fistName, 
      lastName,
      email,
      address,
      phone,
      description
    }

    console.log(data)
 }

  return (
    <>
      <Head>
        <title>Form com NextJS e Chakra UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Flex
          minHeight='100vh'
          width='full'
          align='center'
          justifyContent='center'
          backgroundColor='gray.900'
        >
          <Box px={12} py={12} width='full' maxWidth='450px' textAlign='center'
            boxShadow='lg' borderRadius='6px' background='gray.700'>
            <Heading>
              <Text color='gray.200' fontSize='2xl'>
                Formulário de Registro
              </Text>
            </Heading>
            <Box>
              <form action="" autoComplete='off' onSubmit={handlerSubmit}>
                <Flex justify='space-between'>
                <FormControl isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >First Name</FormLabel>
                  <Input 
                  type='text' 
                  name='fistName' 
                  border='none' 
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='first name'
                  onChange={(e) => setFirstName(e.target.value)}
                  />
                </FormControl>
                <FormControl  isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >Last Name</FormLabel>
                  <Input 
                  type='text'
                  name='lastName'  
                  border='none' 
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Last name'
                  onChange={(e) => setLastName(e.target.value)}/>
                </FormControl>
                </Flex>
                <FormControl  isRequired marginTop='15px' >
                  <FormLabel color='gray.200' > Your e-mail</FormLabel>
                  <Input 
                  type='text'
                  name='email'   
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Your e-mail'
                  onChange={(e) => setEmail(e.target.value)}/>
                </FormControl>
                <Flex justify='space-between' >
                <FormControl  isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >Your address</FormLabel>
                  <Input 
                  type='text' 
                  name='address'   
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Your address'
                  onChange={(e) => setAddress(e.target.value)}/>
                </FormControl>
                <FormControl  isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200' >Your phone</FormLabel>
                  <Input 
                  type='number'
                  name='phone'   
                  outline='none' 
                  bgColor='gray.900' 
                  focusBorderColor='gray.600' 
                  color='gray.200' 
                  placeholder='Your phone'
                  onChange={(e) => setPhone(e.target.value)}/>
                </FormControl>
                </Flex>
                <FormControl  isRequired marginTop='15px'>
                  <FormLabel color='gray.200' >Your descript message</FormLabel>
                  <Textarea 
                    outline='none' 
                    name='description'   
                    bgColor='gray.900' 
                    focusBorderColor='gray.600' 
                    color='gray.200' 
                    placeholder='Your descript message'
                    resize='none'
                    onChange={(e) => setDescription(e.target.value)}
                    />
                </FormControl>
        
                <Button
                  type='submit'
                  width='full'
                  bgColor='green.400'
                  mt={4}
                  color='gray.200'
                  _hover={{color: 'black'}}
                >Cadastro</Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  )
}

export default Home;
